### ISSUE TITLE
DOC: Moving reference material from `structured array` doc in NumPy fundamentals to API reference

### ISSUE THREAD

**Issue by Mukulikaa** [Mukulikaa/numpy#1]
The [Structured arrays](https://numpy.org/devdocs/user/basics.rec.html) page in NumPy fundamentals is very useful and easy to understand. Only the [Recarray Helper Functions](https://numpy.org/devdocs/user/basics.rec.html#module-numpy.lib.recfunctions) subsection seems to be reference material so I think we can move it to API reference. I am not sure exactly where we can place this material though. Maybe we can add it under [numpy.rec](https://numpy.org/devdocs/reference/arrays.classes.html?highlight=rec#record-arrays-numpy-rec) ? Also, I have checked that it is not duplicate material and does not already exist in the reference.

cc: @melissawm @rossbar

**Comment by melissawm** [comment]
If you check the source file for this page, `doc/source/user/basics.rec.rst`, you'll see that the section on Helper Functions is indeed coming from the API reference, so that content is already there. It is included here for convenience, I guess. So I'm not sure we should move it.

**Comment by rossbar** [comment]
If anything I would advocate for removing it entirely, though that will be a much tougher sell to the community. IMO, the `recfunctions` module is almost entirely outdated - I wouldn't point new users to anything in that module except in very minor corner cases. Generally, if you have tabular data for which you need these types of operations, you should be using pandas instead, which is custom-designed for such use-cases.

As it stands though, I agree with Melissa - it may be difficult to figure out how to organize this any better, since the module itself is kind of an awkward fit.

**Comment by Mukulikaa** [comment]
> ...you'll see that the section on Helper Functions is indeed coming from the API reference, so that content is already there.

I think we can only access that content through User Guide -> NumPy fundamentals -> Structured arrays -> Recarray Helper Functions, instead of through the [API reference](https://numpy.org/devdocs/reference/index.html) part of the documentation. It isn't there in the `/reference` directory. Is that something we should address?

**Comment by rossbar** [comment]
You're right that there is no direct reference to the `recfunctions` in the API reference guide. Generally speaking, you're exactly right: all of numpy's functionality *should* be documented in the API reference guide. In this case though, for the reasons mentioned above, the omission may actually be a good thing --- it might make it easier to de-emphasize and perhaps ultimately remove this module.

Rather than adding `recfunctions` to the reference guide, I'd like to use what you've discovered as a motivation to see if we can't work up any momentum to remove it :)

**Comment by Mukulikaa** [comment]
I'll close this issue as I don't need to do anything regarding this doc right now.
