### ISSUE TITLE
DOC: `Writing custom array containers` in NumPy fundamentals can be categorized as a tutorial

### ISSUE THREAD

**Issue by Mukulikaa** [Mukulikaa/numpy#2]
The [Writing custom array containers](https://numpy.org/devdocs/user/basics.dispatch.html) document seems to be a good tutorial instead of an explanation because it 

- has a learning objective,
- gives results immediately,
- begins at the beginning; there are no steps to be executed before the first one,
- ends with a definite outcome; the user implements their own array container,
- and is reproducible.

Also, phrases like "Notice that the return type is...", "We will do x", etc. are used.

I think we can rewrite some parts and make the doc conform to NumPy's tutorial format. Granted it does not have a storyline like the recent tutorials, we can still add it to them I guess?

Note: There is a slight error in the `__init__` method of the example; it should be `self.i = value` instead of `self._i = value`. Right now if we try to reproduce the example it gives an `AttributeError: 'DiagonalArray' object has no attribute 'i'`. If it is a priority I will fix that before updating the rest of the doc.

Let me know your thoughts @melissawm and @rossbar!

**Comment by rossbar** [comment]
IMO this document is intended more to be an explanation than a tutorial, despite the potentially misleading title.

I interpret this document as encapsulating "this is the right way to expand on the ndarray structure, instead of subclassing". That said, I think adding an *additional* tutorial on creating a custom array container with a non-trivial example would indeed be valuable.

I generally think [the documentation surrounding the special array methods](https://numpy.org/devdocs/reference/arrays.classes.html?highlight=__array__#special-attributes-and-methods) would benefit greatly from more examples and expanded info on typical use-cases etc.

**Comment by melissawm** [comment]
I agree with @rossbar  - I think this is explanation material, but having a tutorial on this could be helpful.

**Comment by Mukulikaa** [comment]
> "this is the right way to expand on the ndarray structure, instead of subclassing"

Thanks for giving me this perspective. It does make sense to see it as an explanation this way. I was confused because the [Diataxis framework](https://diataxis.fr/explanation/#about-explanation) says that explanations should not have a _close-up view of the machinery_. But now I can see that the explanation would be the example itself.

>  I think adding an additional tutorial on creating a custom array container with a non-trivial example would indeed be valuable.
> I generally think the documentation surrounding the special array methods would benefit greatly from more examples and expanded info on typical use-cases etc.

I will make a note of this for future improvements. Thanks!

**Comment by rossbar** [comment]
> Thanks for giving me this perspective. It does make sense to see it as an explanation this way.

No problem - this case is particularly tricky because this article is very closely related to the [next article](https://numpy.org/devdocs/user/basics.subclassing.html) on subclassing, which goes into a lot more depth (most of which can in principle be avoided by using the special array methods *instead* of subclassing).

That said - I still find this entire topic confusing :)

**Comment by Mukulikaa** [comment]
Since we don't have to update this document, I'll close this issue!
